### ISSUE TITLE
Compatibility with recen version ?

### ISSUE THREAD

**Issue by fgallese** [NodeBB/nodebb-plugin-global-chat#4]
Hello,

So, I was trying this plugin, and noticed that when I try to access the plugin configuration from the gui, it gets stuck loading the page.

Is this a bug or am I doing something wrong ? I am using nodebb version 1.10.2, cause 1.11.1 doesn't seem to be compatible with this plugin.

In the logs, the only error I see is this, but it doesn't seem to be completely related cause this error it is not caused by trying to access the plugin configuration page:

```
2019-01-14T08:11:46.920Z [16292] - error: /admin/plugins/global-chat
 Error: Failed to lookup view "admin/plugins/global-chat" in views directory "/home/vagrant/nodebb/build/public/templates"
    at Function.render (/home/vagrant/nodebb/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/home/vagrant/nodebb/node_modules/express/lib/response.js:1008:7)
    at content (/home/vagrant/nodebb/src/middleware/render.js:84:15)
    at /home/vagrant/nodebb/node_modules/async/dist/async.js:3880:24
    at replenish (/home/vagrant/nodebb/node_modules/async/dist/async.js:1011:17)
    at /home/vagrant/nodebb/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/home/vagrant/nodebb/node_modules/async/dist/async.js:1041:24)
    at /home/vagrant/nodebb/node_modules/async/dist/async.js:1046:16
    at eachOf (/home/vagrant/nodebb/node_modules/async/dist/async.js:1117:5)
    at _parallel (/home/vagrant/nodebb/node_modules/async/dist/async.js:3879:5)
    at Object.parallelLimit [as parallel] (/home/vagrant/nodebb/node_modules/async/dist/async.js:3962:5)
    at /home/vagrant/nodebb/src/middleware/render.js:79:12
    at nextTask (/home/vagrant/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/home/vagrant/nodebb/node_modules/async/dist/async.js:5331:9)
    at /home/vagrant/nodebb/node_modules/async/dist/async.js:969:16
    at /home/vagrant/nodebb/node_modules/async/dist/async.js:473:16
```
Any ideas that could help me figure it out ?

Thank you

**Comment by fgallese** [comment]
Nevermind, I figured out I had to run rebuild before restart.. My bad.
